server {
  listen 80;

  location /jeecgboot/ {
    proxy_pass http://backend:8080/jeecg-boot/;
    proxy_redirect off;
    proxy_set_header Host backend;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
  }

  location / {
    root /var/www/html/;
    index index.html index.htm;
    if (!-e $request_filename) {
      rewrite ^(.*)$ /index.html?s=$1 last;
      break;
    }
  }

  access_log /var/log/nginx/access.log;
}

